language: php
php:
  - 5.6
  - 7.0

matrix:
  allow_failures:
    - php: 7.0

before_script:
 - cd src/
 - travis_retry composer self-update
 - travis_retry composer install --no-interaction

script:
 - mkdir -p build/logs
 - php vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_script:
 - ls -l build/logs/
 - travis_retry php vendor/bin/coveralls -v
