language: php
php:
  - 5.6
  - 7.0

matrix:
  allow_failures:
    - php: 7.0

cache:
  directories:
    - vendor

before_script:
 - cd src/
 - find . -name "*.php" ! -path '*/_ide_helper.php' -print0 | xargs -0 -n1 -P8 php -l
 - travis_retry composer install --no-interaction

script:
 - mkdir -p build/logs
 - php -d max_execution_time="600" -d memory_limit="512M" vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_script:
 - ls -l build/logs/
 - travis_retry php vendor/bin/coveralls -v
