language: php
php:
  - '5.6'
  - '7.0'

before_script:
 - cd src/
 - pwd
 - wget http://getcomposer.org/composer.phar
 - php composer.phar install --dev --no-interaction

script:
 - pwd
 - mkdir -p build/logs
 - phpunit --coverage-clover build/logs/clover.xml

after_script:
 - pwd
 - php vendor/bin/coveralls -v
