version: '2'
services:
  localdevbase:
    build:
      context: .
      dockerfile: docker/localdev/Dockerfile
    ports:
      - "8080:80"
    volumes:
      - "./:/app"
    environment:
      - VHOSTNAME=vagrant.tmlpstats.com
      - APP_DEBUG=true
      - DB_HOST=mysql
      - MEMCACHED_HOST=memcached

  # The "localdev" docker image is a developer image
  localdev:
    extends:
      service: localdevbase
    volumes:
      - "/app/src/vendor"
    links:
      - mysql
      - memcached

  # The "local" docker image is a much faster PHP executor because it makes vendor a volume.
  local:
    extends:
      service: localdevbase
    volumes:
      - "/app/src/vendor"
    links:
      - mysql
      - memcached


  mysql:
    build:
      context: docker/mysql
    ports:
      - "3306:3306"

  memcached:
    image: memcached:1.4-alpine
